- name: Configure Database Server
  hosts: dbserver
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Update APT repositories
      apt:
        update_cache: yes

    - name: Install required Python MySQL library
      apt:
        name:
          - python3-pymysql
        state: present

    - name: Install MySQL server and phpMyAdmin
      apt:
        name:
          - mysql-server
          - phpmyadmin
        state: present

    - name: Configure MySQL root user with password
      shell: |
        mysql -u root -p123 -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '123';"
        mysql -u root -p123 -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '12345';"
        mysql -u root -p123 -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"
        mysql -u root -p123 -e "FLUSH PRIVILEGES;"


    - name: Configure phpMyAdmin
      copy:
        content: |
          Alias /phpmyadmin /usr/share/phpmyadmin

          <Directory /usr/share/phpmyadmin>
              Options FollowSymLinks
              DirectoryIndex index.php
              Require all granted
          </Directory>
        dest: /etc/apache2/conf-available/phpmyadmin.conf

    - name: Enable phpMyAdmin configuration
      command: a2enconf phpmyadmin

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: true
